name: "🐛 Bug report"
description: "Сообщить об ошибке в моде"
title: "[BUG] <опишите проблему>"
labels: ["bug"]
assignees: ["Dima345200"]

body:
  - type: textarea
    id: what-happened
    attributes:
      label: "🐛 Что произошло?"
      description: "Опишите проблему"
      placeholder: "Например: игра вылетает при открытии сундука"
    validations:
      required: true

  - type: input
    id: mc-version
    attributes:
      label: "🎮 Версия Minecraft"
      placeholder: "1.20.1 (Fabric / Forge / Neoforge)"
    validations:
      required: true

  - type: input
    id: mod-version
    attributes:
      label: "📦 Версия мода"
      placeholder: "v1.0.0"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "📄 Логи (latest.log)"
      description: "Отправьте содержимое файла latest.log или crash-report"
    validations:
      required: false
